// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilqurbm9GnK5SWfYy40a-Jl7Zoubx2bY',
    appId: '1:93394752698:web:0fe2732998b5f7604d1e83',
    messagingSenderId: '93394752698',
    projectId: 'dashboard-4c650',
    authDomain: 'dashboard-4c650.firebaseapp.com',
    storageBucket: 'dashboard-4c650.appspot.com',
    measurementId: 'G-THY6SYWW8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOvvEW5eCtPygowyzri440Pw2kpP5OvR8',
    appId: '1:93394752698:android:1b56b1cbb49071304d1e83',
    messagingSenderId: '93394752698',
    projectId: 'dashboard-4c650',
    storageBucket: 'dashboard-4c650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqyBuAhKkx59gI0DthNCCNlGrNzWQDjCI',
    appId: '1:93394752698:ios:18c784616578067d4d1e83',
    messagingSenderId: '93394752698',
    projectId: 'dashboard-4c650',
    storageBucket: 'dashboard-4c650.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqyBuAhKkx59gI0DthNCCNlGrNzWQDjCI',
    appId: '1:93394752698:ios:18c784616578067d4d1e83',
    messagingSenderId: '93394752698',
    projectId: 'dashboard-4c650',
    storageBucket: 'dashboard-4c650.appspot.com',
    iosBundleId: 'com.dashboard.flutter.app.flutterDashboard',
  );
}
